### ISSUE TITLE
SPED Fiscal

### ISSUE THREAD

**Issue by leandrossantos** [samuelroliveira/SPEDBr#1]
Baixei os fontes do projeto, gostaria de saber como está a parte de SPED Fiscal?

Já está toda funcional?

**Comment by samuelroliveira** [comment]
Olá @leandrossantos 
Atualmente para o SPED Fiscal somente o Bloco 0 está completo na biblioteca, eu comecei a pouco tempo esse trabalho e tive que fazer uma pausa para mapear as classes da EFD Contribuições. Um cliente tinha a necessidade de enviar a DIMOB e a EFD Contribuições com inf. imobiliárias. Para a EFD Contribuições já funciona o bloco F (para regime caixa sim, competência ainda não), M, 1.

Em resumo, tem bastante coisa para fazer ainda no SPED Fiscal, mas acho que até o final do mês consigo fazê-lo. Caso queira me ajudar podemos dividir os blocos e cada faz uma parte. Podemos conversar via Skype para facilitar a comunicação.

-- Samuel Rocha

**Comment by douglashferreira** [comment]
Bom dia @samuelroliveira você poderia passar seu contato do Skype, gostaria de entender melhor sua ideia e se possivel nos ajudar com esse projeto do SPED, pois aqui na empresa que trabalho iremos precisar, e tendo mais pessoas fazendo facilita para todos.
caso queira me adicionar meu skype eu uso o email: douglas_datasystem@hotmail.com

Douglas H. Ferreira

**Comment by samuelroliveira** [comment]
Olá @douglashferreira a intenção desse projeto é centralizar a "sujeira" das classes do SPED em um só lugar. Como desenvolvedores estamos sempre meios de manter nossos projetos limpos. Há pouco tempo iniciei o projeto mas acredito que em breve já teremos uma grande parte do layout adaptado nesse formato de mapeamento para geração das informações via Reflection.
PS: Já te add no Skype.
Abraços.

-- Samuel Rocha

**Comment by leandrossantos** [comment]
@samuelroliveira mais alguma novidade no projeto de SPED? Já tem alguns dias que não tem commit aqui.

**Comment by samuelroliveira** [comment]
Fala @leandrossantos, tudo na paz?

Bom cara... Estou envolvido em outro projeto e por isso não estou tendo muito tempo para mapear novos layouts aqui no SPEDBr. Mas irei retomar os commits aos finais de semana que pelo menos assim não fica parado por muito tempo.
Abraços.

-- Samuel Rocha

**Comment by leandrossantos** [comment]
Opa @samuelroliveira blz Samuel, valeu.
Também estou aqui agarrado com os tais de MDFe e CTe.

**Comment by leandrossantos** [comment]
@samuelroliveira alguma novidade no projeto de SPED ??

**Comment by samuelroliveira** [comment]
Fala @leandrossantos, tudo na paz?
Fiquei um tempo sumido, por motivos de trabalho mesmo, até o final de Julho os escritórios contábeis estão todos ocupados com declarações da Receita e tantas outras coisas que quem trabalha direta ou indiretamente fica no meio do fogo cruzado. o/
Mas estamos aí novamente, a todo vapor pra concluir esse projeto.

No último commit eu modifiquei tela de apresentação do DEMO. E breve irei incluir novos mapeamentos, testes e melhorias nas telas do projeto.

Att,
Samuel Rocha

**Comment by leandrossantos** [comment]
Oi @samuelroliveira baixei novamente o projeto, mais não entendi e não achei a chamada para gera o SPED ou o Sintegra que seja. Eu executo o exemplo clico mais não faz nada.

**Comment by samuelroliveira** [comment]
@leandrossantos após meu último commit as telas de Sintegra e SPED Fiscal ainda não estão "linkadas", na verdade irei fazer novas telas de apresentação com uma geração de informações resumidas para servir de exemplo.

Com relação às chamadas para geração dos arquivos:

Primeiro preencha o objeto - registro por registro - e após chame o método _EscreverCampos_.
Depois de uma olhada na classe **_EscreverCamposSpedByAttribute_**, essa classe é responsável por gerar as informações linha a linha.

```cs
// SPED Fiscal
var reg0000 = new SpedFiscal.Bloco0.Registro0000();

reg0000.Cnpj = "01.234.567/0008-99";

var result = reg0000.EscreverCampos(new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1));
```
![](https://s19.postimg.org/c8zcqrh8z/cap_1.png)
PS¹: A competência (data do arquivo) é passada como parâmetro para ser avaliado caso tenha algum registro no SPED que não seja obrigatório.
PS²: Observe que é feita a validação dos campos enquanto a geração das informações nas linhas é feita. Neste caso, não foi preenchido o campo **_NOME_** (Razão Social).

No caso do SINTEGRA, como o mapeamento ainda não foi trocado para Reflection é do jeito antigo mesmo. Veja um exemplo de geração no userControl do Sintegra "ucSintegra".

**Geração dos Registros 10 e 11**
![](https://s19.postimg.org/ehdj83ocz/cap_2.png)

**Geração dos Registros de Documentos e Encerramento**
![](https://s19.postimg.org/pjn7ka7tf/cap_3.png)

PS³: Quando eu fiz essa codificação para gerar o SINTEGRA eu tinha urgência em gerar só os registros 50 e 61, eu fiz a importação de uma planilha e gerava as informações conforme o layout pede.

Espero ter ajudado. Caso tenha mais dúvidas é só postar.
Att,
Samuel Rocha

**Comment by leandrossantos** [comment]
E ai @samuelroliveira novidades no projeto de SPED ?

**Comment by eduprog** [comment]
@leandrossantos , pelo que ele me passou, esta semana mesmo estará disponibilizando novas partes do projeto.

**Comment by samuelroliveira** [comment]
@leandrossantos e @eduprog no último commit estão mapeadas as classes até o Registro C495 do Sped Fiscal. Logo mais trarei mais atualizações.

Abraços.

**Comment by leandrossantos** [comment]
@samuelroliveira e ai tem mais novidades no projeto SPEDBr ??

Já esta gerando todo o SPED Fiscal incluindo o Bloco K ??

**Comment by samuelroliveira** [comment]
Fala @leandrossantos, na paz?

Hoje - 20/11 - estarei finalizando os registros E, G, H, K e 1.

No decorrer da semana irei fazer o restante do D.

E logo após já irei atualizar o layout para a versão 19, a ser utilizada em 2017 e retomar os mapeamentos na EFD Contribuições.

Abraços.

**Comment by leandrossantos** [comment]
Opa @samuelroliveira então o SPED Fiscal está quase pronto, é isso?

**Comment by samuelroliveira** [comment]
Isso mesmo @leandrossantos. \o/

**Comment by rbarins** [comment]
Bom dia, @samuelroliveira você poderia passar o seu contato do Skype !! Estou com umas duvidas referente ao seu projeto

**Comment by samuelroliveira** [comment]
@rbarins Meu Skype é samueltcskp.

**Comment by samuelroliveira** [comment]
@douglashferreira você chegou a fazer algum teste de velocidade na geração dos arquivos? Como está? Satisfatório? Eu estava pesquisando maneiras de tornar mais rápida a geração. Vou fazer umas pequenas mudanças para passar pelos laços de validação e geração mais rápido. Apesar de ter adaptado que a lib gere nos padrões aceitáveis ainda não estou convencido da velocidade. Pode me retornar com um feedback assim que possível?

**Comment by EltonRst** [comment]
@samuelroliveira Muito bom o Projeto, mas como iniciante e leigo aqui tenho algumas perguntas:

Como está o Andamento dos Blocos do "SpedBr.SpedFiscal" ? Preciso dos Blocos: 0,  C  e  9.
Alguém pode me disponibilizar um exemplo com esses blocos implementados ?
E como eu posso contribuir para com o Projeto ?

Se alguém quiser ou puder me dar uma aula de GitHub com Visual Studio eu ficaria muito agradecido, tenho dificuldades por que sempre usei outros softwares para versionamento.

**Comment by samuelroliveira** [comment]
Fala @EltonRst, tudo na paz? Vamos lá..
O SPED Fiscal está quase (falta somente alguns poucos registros do Bloco D) todo implementado.
Alguns exemplos básicos de uso podem ser achados na solution de testes, dentro do projeto mesmo (SpedBr.Tests). 

Mas aqui vou te deixar um exemplo da implementação do Bloco C:
````cs
var minhaNotaFiscalEletronica = new RegistroC100();

minhaNotaFiscalEletronica.IndOper = 0; // 0 para Entrada ou 1 para Saída
minhaNotaFiscalEletronica.IndEmit = 0; // 0 para Emissão própria ou 1 para Terceiros

// Aqui vai uma dica:
// Para os códigos de participantes (fornecedores de mercadorias, clientes, transportadoras, administradoras de cartões, etc) eu costumo usar o CNPJ/CPF.
minhaNotaFiscalEletronica.CodPart = FBR99999; // código do fornecedor da mercadoria ou código do cliente caso o indicador da operação seja 1 (Saída)
minhaNotaFiscalEletronica.CodMod = 55; // NF-e
minhaNotaFiscalEletronica.CodSit = 00; // Regular
minhaNotaFiscalEletronica.Ser = 1; // Série da nota
minhaNotaFiscalEletronica.NumDoc = 123456789; // Número da nota
minhaNotaFiscalEletronica.ChvNfe = "CHAVE_DA_NFE_COMPOSTO_POR_44_CARACTERES";

[...]

// Esse é um exemplo simples de preenchimento da nota na mão mas, quando você o fizer será necessário colocar dentro de um foreach.

foreach (documentoFiscalAtual in listaDocumentosFiscais)
{
var documentoFiscal = new RegistroC100();
// Aqui você busca as informações de cada documento e vai preenchendo.

// Dentro deste mesmo foreach preencha os dados dos itens, criando um registro C170 para cada produto/serviço da nota fiscal.

// Vá adicionando tudo em uma lista de strings desta forma:
linhasArquivoTxt.Add(documentoFiscal.EscreverCampos());
}

````

Caso queira contribuir com o projeto, basta fazer o mapeamento das classes conforme os já existentes e fazer um pull request para a lib, que eu analiso e aprovo.

Aqui vai um link de como funciona o Git no Visual Studio. Há vários exemplos no YouTube também.
https://social.technet.microsoft.com/wiki/pt-br/contents/articles/32376.utilizando-o-github-no-visual-studio-2015.aspx

Abraços.

**Comment by EltonRst** [comment]
@samuelroliveira Muito obrigado pelas dicas, só ainda não entendi bem a funcionalidade de dar um "Fork"
no Repositório, não sei se eu clono o "Fork" que eu fiz ou se eu clono direto o repositório Original, quando
você atualiza o Repositório Original esse meu Fork é atualizado também, e se eu clono o Fork, quando eu faço commit vai pro Fork ou Original, kkkkkkkk estou meio confuso.

Cara já estou usando o Projeto e está ótimo, tudo bem organizado, compreensível e Funcional.

**Comment by samuelroliveira** [comment]
@EltonRst quando você clona o projeto independente das alterações você pode fazer um sync depois que será possível escolher quais mudanças irão permanecer e quais mudanças irão sair.
Caso suas alterações não sejam particulares de forma a modificar o fluxo da lib pode fazer o pull request, que assim que eu aprovar, você mantém suas mudanças e obtém as atualizações mais recentes da lib.

O funcionamento do Git é muito simples, logo logo você pega o jeito.

Obrigado pelo feedback, caso tenha dúvidas é só postar.

Abraços.
