### ISSUE TITLE
SPED Contribuições

### ISSUE THREAD

**Issue by marcosgerene** [samuelroliveira/SPEDBr#10]
Bom dia,

Vi que o SPED Fiscal está pronto (e completo), procede? blocos "novos" como o K já funcionam?

Agora, saindo do SPED Fiscal, existe algo já feito ou previsão para desenvolvimento do SPED Contribuições?

**Comment by samuelroliveira** [comment]
@marcosgerene Para o SPED Fiscal ficar completo só faltam alguns registros do BLOCO D, que são utilizados por concessionárias de energia elétrica e demais registros que consolidam as informações, tais como, modais rodoviários, ferroviários, aquaviários, etc.. Esse tipo de registro acompanha uma particularidade muito grande. __O SPED Fiscal para uso comercial como estamos acostumados a trabalhar está pronto, mas não completo ainda__.

No caso da EFD Contribuições tenho a parte imobiliária feita pois precisei desenvolver a DIMOD e essa parte para um cliente. Já os demais registros de documentos fiscais, gestão de créditos, notas de serviço com retenções e demais particularidades de arquivos no perfil consolidado ou detalhado ainda está para fazer. Meu tempo ultimamente está muito escasso, na medida do possível vou fazendo aos poucos mas se quiserem podem ir mapeando e "subindo" pull requests que vou analisando e aprovando.

Abraços.

**Comment by marcosgerene** [comment]
@samuelroliveira 

Cara, infelizmente estou na mesma que você quanto a tempo, você (ou alguém na comunidade) tem interesse em um "patrocínio" para focar no SPED Contribuições (desenvolvimento para comercio no geral)?

Eu até poderia mapear e fazer o PR, mas meu cliente tem pressa e meu tempo está absurdamente escasso rs

Abraços

**Comment by samuelroliveira** [comment]
Me passa seu e-mail ou seu Skype.

**Comment by danielgamajpa** [comment]
Boa noite, estou cooperando com este projeto. está ficando show de bola. 
Adicionei recentemente os blocos do SPED Contribuições:

A - (A010, A100, A110, A170) 
C - (C010, C100, C110, C170, C175, C180, C181, C185, C190, C191, C195, C199, C380, C381, C385, C500, C501, C505)
F - (F100, F550, F600)

Meu foco é justamente para o Comércio em Geral.

Aguardando só a revisão de @samuelroliveira 
Ainda estou meio "iniciante" no github mas acredito que esteja colaborando corretamente.

**Comment by samuelroliveira** [comment]
Valeu @danielgamajpa o/

Fiz a aprovação do Bloco F agorinha mesmo, fiz só algumas alterações pois alguns campos estavam com a quantidade de casas decimais menor do que o previsto no manual e alguns campos com tamanho de campo diferente também.

Mas obrigado pela colaboração.

Abraços.

**Comment by marcosgerene** [comment]
@samuelroliveira O que eu quero é justamente o que o @danielgamajpa disse, meu e-mail é mgf.spirito@gmail.com

**Comment by marcosgerene** [comment]
Boa noite @samuelroliveira,

Tem alguma previsão de qdo o pull do @danielgamajpa será aceito? Aguardo ansiosamente rs

**Comment by samuelroliveira** [comment]
@marcosgerene vou revisar os PR abertos hoje mesmo.

Véspera de imposto de renda é canseira. o/

**Comment by marcosgerene** [comment]
@samuelroliveira 
Aprendi como pegar pulls de terceiros no meu fork, ficou bem mais facil agora, vou virar praticamente um beta tester rsrs

**Comment by samuelroliveira** [comment]
@marcosgerene desculpa a demora. Aceitei todos os pulls abertos e corrigi alguns detalhes que tinham sido mencionados anteriormente. Qualquer coisa é só falar.

**Comment by eduprog** [comment]
Amigo neste link o manual detalhado e bem explicativo.  https://www.google.com.br/url?sa=t&source=web&rct=j&url=http://sped.rfb.gov.br/estatico/20/4E78FBAD67086070031C828FDAEF8F5DD19BD0/Guia_Pratico_EFD_Contribuicoes_Versao_1_22.pdf&ved=2ahUKEwj1-JWZ0I_cAhUJlZAKHX3jCCoQFjAAegQIBRAB&usg=AOvVaw04m9LNxmO-wvaq2ooyXBXn
