### ISSUE TITLE
HELP com o Bloco 0

### ISSUE THREAD

**Issue by EltonRst** [samuelroliveira/SPEDBr#14]
@danielgamajpa 
@samuelroliveira 
ocorre comigo no Bloco 0, Registros 0190 e 0200:

no Registro 0190 ele coloca a unidade de Medida com:
|0190|0000UN||
|0190|0000ML||
Sem a Descrição assim mesmo.

e no Registro 0200 acontece:
|0200|1||||0000UN|00|84821010||84||18,00|
|0200|1119||||0000ML|00|84829119||84||18,00|

Sem a Descrição e alguns dados do Produto.

Alguém pode me ajudar ? OBS: montei os objetos dos Registros com todos os dados certinhos.

Mais uma coisa, como eu faço um UPDATE no meu FORK, e depois como eu faço um PULL Request com as Alterações ?

**Comment by douglashferreira** [comment]
entra no cadastro dos blocos e altera o TIPO do campo de "C" para outra coisa eu coloquei "T" no meu fonte como o tamanho do campo é 6 ele coloca 0's à esquerda quando o tipo é "C" - Código.

**Comment by EltonRst** [comment]
@douglashferreira A princípio não mudou nada aqui, vou revisar esse algoritmo de escrever os campos, eu só precisaria de ajuda com o GitHub mesmo, pois ainda não sei fazer um UPDATE do meu FORK apartir do projeto ORIGINAL (master), eu não sei se o FORK atualiza sózinho junto com o master ou o que, para depois fazer as alterações no meu projeto, fazer um COMMIT no meu FORK e depois um PULL REQUEST no 
Projeto ORIGINAL (master).

Ainda estou perdido aqui no GitHub, eu uso TORTOISE SVN e VISUAL SVN no trabalho e eles são muito diferentes.

**Comment by douglashferreira** [comment]
@EltonRst no meu 0200 eu coloquei assim para não colocar os 0's
em relação ao GIT, eu mandei algumas coisas mas depois fiz tanta caca que deletei meu fork e refiz o fork atualizado hahahaha
me perco até hoje ainda...
`[SpedCampos(6, "UNID_INV", **"T"**, 6, 0, true)]
            public string UnidInv { get; set; }`

**Comment by danielgamajpa** [comment]
@EltonRst Boa Tarde,

você deverá alterar na classe **EscreverCamposSpedByAttribute**
linha 90/91

o seguinte trecho:

`var isCodeOrNumberAndHasLength = (spedCampoAttr.Tipo == "C" || spedCampoAttr.Tipo == "N") &&(spedCampoAttr.Tamanho > 0 && spedCampoAttr.Tamanho <= 10);`

para:
`var isCodeOrNumberAndHasLength = (spedCampoAttr.Tipo == "C" || spedCampoAttr.Tipo == "N") &&(spedCampoAttr.Tamanho > 0 && spedCampoAttr.Tamanho <= 4);`

Isso remove os 0000 do começo da unidade de medida.
Já que este trecho de código faz com que todos os campos que são do tipo C ou N e tenham até 10 caracteres, seja completado com 0 a esquerda. 
Acredito que o @samuelroliveira quando criou isso, foi para campos referente a "Número de Série" e "CSTs" que necessitam serem preenchidos com 0 a esquerda, (mesmo colocando o CST como 1), acredito também que não tenha necessidade de outros campos com mais de 4 caracteres serem preenchidos com 0 a esquerda.

Referente a Descrição do Item, no Model do 0190 
onde tem o seguinte trecho:
 `[SpedCampos(3, "DESCR", "C", 0, 0, true)]`
` public string Descr { get; set; }`

coloque o seguinte:
 `[SpedCampos(3, "DESCR", "C", int.MaxValue, 0, true)]`
` public string Descr { get; set; }`

**Comment by samuelroliveira** [comment]
Fala pessoal, obrigado pelos comentários, irei fazer as devidas correções.

@danielgamajpa foi exatamente como você disse, coloquei para completar com zeros quando fossem CST e Série mesmo mas há outros casos que ainda se aplicam, poucos mas existem. Se eu não estiver equivocado, quando estudei o manual da EFD somente 2 ou 3 casos tinham zeros à esquerda com mais de 4 caracteres. Irei revisar e corrigir isso.

**Comment by EltonRst** [comment]
Muito obrigado pelas dicas, assim que eu me achar com o GitHub aqui, se não houver PULL para as correções eu tento fazer ;)

**Comment by samuelroliveira** [comment]
@EltonRst Acesse o http://sped.rfb.gov.br/ no menu Downloads e baixe o validador que você necessitar.

A opção Validador EFD ICMS-IPI é para validar o arquivo do SPED FISCAL (ICMS/IPI).

**Comment by EltonRst** [comment]
Amigos, quando eu abro um PULL REQUEST para um arquivo, mesmo eu fazendo commits no meu FORK para outros arquivos após, eles ficam na Fila até alguém autorizar e dar MERGE no master ? se for assim eu já fiz alguns Ajustes no meu FORK pra poder colocar o SPEDBr em produção, e o PULL já está feito.

**Comment by marcosgerene** [comment]
Estou com o mesmo problema, em qual pull esta a correção? vou puxar para meu fork este pull

**Comment by samuelroliveira** [comment]
Fala pessoal, tudo na paz? Desculpa o sumiço, ainda estou envolvido com ECF e o tempo está bem escasso.
Bom... boa parte de todos os issues que vocês relataram já foram resolvidos nos PR mas, se tiver mais alguma coisa é só ir postando, na margem do possível vamos fazendo.
Aproveitando, a correção do tamanho de campos do tipo "C" foi feita em um PR mas alterei também o tipo do campo Unid para "ACM" (Acrônimo) para não correr o risco de esbarrarmos nesse tipo de inconsistência novamente.

Abs.
