### ISSUE TITLE
Registro C500 - Sped Fiscal

### ISSUE THREAD

**Issue by marcosgerene** [samuelroliveira/SPEDBr#16]
Bom dia @samuelroliveira 

No registro C500 no sped fiscal:

1. O campo "NumDoc" está como Double... não deveria ser Int/Long?

2. Os campos VlPiS e VlCofins estão como decimal, mas acredito que deveriam ser "decimal?" (nullable), pois não são obrigatórios

3. Os campos TpLigacao e CodGrupoTensao estão com "int", acredito que deveriam ser "int?" pois ambos não são obrigatórios.

Att

**Comment by samuelroliveira** [comment]
Bom dia @marcosgerene,

Já aprovei seu PR. Todas as alterações foram devidas. Obrigado o/
