### ISSUE TITLE
Bloco E - Registros E001 e E100

### ISSUE THREAD

**Issue by marcosgerene** [samuelroliveira/SPEDBr#19]
Alguns atributos como "IND_MOV" , "DT_INI" e "DT_FIN",  estão fora dos padrões do projeto "IndMov", "DtIni", "DtFin", isto é intencional?

**Comment by marcosgerene** [comment]
https://github.com/samuelroliveira/SPEDBr/pull/20

**Comment by samuelroliveira** [comment]
@marcosgerene ainda há alguns campos que irei mapear para os Enums e tipos específicos. Mas no começo da lib era ``int` a maioria dos campos de indicadores. Os campos de data no começo do desenvolvimento da lib eram formatados direto em uma propriedade no mapeamento. Estou removendo esses casos aos poucos. Mas sim, foi intencional mas o propósito final não é deixar assim.`

**Comment by marcosgerene** [comment]
@samuelroliveira eu ja havia corrigido via pull, vi que você aceitou meu pull hoje, vou ver o que foi alterado para ajustar meu código, abraço
