### ISSUE TITLE
Abrir Projeto

### ISSUE THREAD

**Issue by hcmg** [samuelroliveira/SPEDBr#22]
Parabéns pelo projeto,
Preciso de ajuda, quando abro o projeto e dou start aparece a mensagem:

visual studio cannot start debugging because the debug target is missing
please build the project and retry or set the outputpath and assemblyname visual 2017

e logo abaixo:
Error	15	Unable to find manifest signing certificate in the certificate store.	SpedBr.AppTeste

Alguem pode ajudar ?

**Comment by samuelroliveira** [comment]
@hcmg removi o manifesto assinado com certificado. Tente novamente.

**Comment by samuelroliveira** [comment]
@hcmg vou fechar esse issue por hora pois não vou deixar projeto Windows Forms nessa biblioteca. Irei transferir tudo para uma outra lib criando um app de teste para consumir esta lib (SPEDBr) e a lib do SintegraBr, centralizar os exemplos em um lugar só.
