### ISSUE TITLE
EFD ICMS/IPI está implementado?

### ISSUE THREAD

**Issue by robertorp** [samuelroliveira/SPEDBr#9]
EFD ICMS/IPI está implementado no projeto já?

Seguinte.. pelo que vimos nossa empresa aqui, aparentemente simples nacional no Seara é obrigatório gerar o mesmo. Logo então teremos que implementar o mais rápido possível. 
Somente queria saber se o mesmo já esta implementado na lib.

**Comment by douglashferreira** [comment]
Boa tarde Roberto, acredito que esteja tudo criado, talvez uma coisa ou outra que possa estar faltando especifico... se for é muito pouco... eu já utilizo ele em produção em empresas do ramo de Calçados e Confecção e está ok.

**Comment by robertorp** [comment]
blz, no meu caso é varejo geral, pode ser uma oficina, pode ser uma mercearia, um supermercado, loja de roupas, confecções também enfim varejo.. (nf-e e nfc-e)

**Comment by douglashferreira** [comment]
utilizamos Cupom Fiscal, SAT, NFCe e NFe e está ok

**Comment by samuelroliveira** [comment]
Fala pessoal, tudo na paz?
Fico feliz em saber que o colega @douglashferreira já utilize.
Enfim, @robertorp fiz todas os mapeamentos de classes com exceção de algumas do Bloco D, não o fiz ainda por falta de tempo, estamos em maratona de fechamento de balanços, DIRF, DIMOB, RAIS e preparando para DEFIS e Imposto de Renda, então está bem complicado.
Mas na medida do possível aos finais de semana eu vou implementando o que precisarem, ou se quiser fazer um pull request com o que faltar, eu aprovo e fica tudo certo.

**Comment by samuelroliveira** [comment]
@robertorp fiz uma pesquisa mais cuidadosa e descobri que algumas empresas do Simples Nacional já estão obrigadas à EFD ICMS/IPI mesmo. Isso está sendo tratado no [Protocolo 03/2011 do CONFAZ](https://www.confaz.fazenda.gov.br/legislacao/protocolos/2011/pt003_11).

Achei estranho a primeira vez que você falou porque você também é de Goiás, correto? Mas deve ter clientes em outras UF.

Em resumo, os Estados que já obrigaram à transmissão do SPED Fiscal ou obrigarão a curto prazo são: 

> Acre, Alagoas, Amapá, Amazonas, Bahia, Espírito Santo, Maranhão, Mato Grosso do Sul, Minas Gerais, Paraíba, Paraná, Piauí, Rio Grande do Sul, Rio de Janeiro, Roraima, São Paulo e Sergipe a obrigatoriedade prevista no caput aplica-se a todos os estabelecimentos dos contribuintes a partir de 1º de janeiro de 2014, podendo ser antecipada a critério de cada um desses Estados.

> O Estado do Rio de Janeiro passou a obrigar a partir de 1º de setembro de 2014, assim que desobrigou o SINTEGRA.

> O Estado de Roraima passou a obrigar a partir de 1º de janeiro de 2015, assim que desobrigou o SINTEGRA.
